### ISSUE TITLE
Init, Build & Deploy

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui-notifications#1]
## Init
Představuju si to tak že bundle bude exportovat do global (`window`) objekt `kbcNotifications` s metodou start která bude mít rozhraní:

```
function start(initialState, rootDOMNode);
```

Nevím jestli manage token cpát do initial state nebo samostatně?

Initial state:
```
{
 "notifications": []
}
```

`rootDOMNode` je uzel do kterého se aplikace vyrenderuje, nemůže to být body apod protože na stránce bude víc React appek.

Je možný že `Redux` nebo ten boilerplate to doporučuje udělat nějak jinak ten boot to by asi taky nebyl problém. Jenom to pak pro to musím připravit na straně KBC, to ale musím udělat tak i tak.

## Build
Build by měl vyplivnout:
 - 1 js soubor
 - 1 css soubor (do kterého nebude zbuildovaný bootstrap ani kbc-bootstrap)
 - manifest ve tvaru:

```json
{ name: 'kbcNotifications',
  version: '0.1.30-104-g27ef623',
  basePath: 'https://kbc-uis.s3.amazonaws.com/kbc-notifications/0.1.30-104-g27ef623/',
  scripts: [ 'https://kbc-uis.s3.amazonaws.com/kbc-notifications/0.1.30-104-g27ef623/bundle.min.js' ],
  styles: [ 'https://kbc-uis.s3.amazonaws.com/kbc-notifications/0.1.30-104-g27ef623/bundle.min.css' ] }
```

Vytvoření manifestu https://github.com/keboola/kbc-ui/blob/master/webpack/generate-manifest.js

## Deploy
- Nahrání buildu do S3 https://github.com/keboola/kbc-ui/blob/27ef62394a2541a6c7b89c3a2633d8703a3a7ae5/.travis.yml#L20
- Registrace a aktivace nové verze v KBC přes manage API (Notifikace budou mít nový token)  https://github.com/keboola/kbc-ui/blob/27ef62394a2541a6c7b89c3a2633d8703a3a7ae5/.travis.yml#L34

**Comment by ondrejhlavacek** [comment]
# Init
hotovo - https://github.com/keboola/kbc-ui-notifications/blob/master/src/index.html#L46

**Comment by ondrejhlavacek** [comment]
Build mi zatím moc nejde, zkusím se na to podívat ještě zejtra.

- v defaultním nastavení to vůbec negeneruje css (domrvil jsem loadery?)
- v buildu je spousta dalších fajlů (fonty) a soubry z https://github.com/keboola/kbc-ui-notifications/blob/master/webpack.config.js#L84 (nechtělo je to jinak loadovat)
- ...

Budu muset nadrtit webpack, jinak s tím nepohnu.

**Comment by ondrejhlavacek** [comment]
Ještě mě napadá - v tom initu chybí informace o tokenu, ne? To tam zatím vůbec nemám - nic se neloaduje.

**Comment by Halama** [comment]
@ondrejhlavacek zajima te ten webpack, nebo se o tohle mam postarat? Ta konfigurace je dost peklo ...

**Comment by Halama** [comment]
k tomu tokenu jsem tam psal poznamku jestli ma byt v initial data nebo samostatne?

**Comment by ondrejhlavacek** [comment]
Jo! Token bych dal do initial state. To tam připravím, až to budu napojovat na API. 

A s tím webpackem - jestli to máš aspoň trochu najetý, dost by mi to píchlo, deploy a zbytek už zvládnu. Jinak mě webpack zajímá, ale ne nijak urgentně.

**Comment by Halama** [comment]
Ok token budu davat do initial state, tim padem tohle rozhrani zustava.

Mrknu teda na ten build. On ten webpack je dobry vedet co umi a co dela ale na tom samotnym konfigurovani imho nic zajimavyho neni.

**Comment by Halama** [comment]
Build je tady https://github.com/keboola/kbc-ui-notifications/pull/3

**Comment by ondrejhlavacek** [comment]
Takhle nějak jsem si myslel že to bude! Díky!

**Comment by Halama** [comment]
Hotovo
